# Konfigurációs beállítások a képkereső alkalmazáshoz
import os
from typing import Dict, Any

# Adatbázis fájl neve
# Render.com-on használj Persistent Disk-et és állítsd be:
# DATABASE_PATH=/var/data/votes.db
DATABASE = os.environ.get('DATABASE_PATH', 'votes.db')

# Az adatmappák elérési útja
DATA_DIR = 'data'

DEFAULT_VIDEO_URL = 'https://www.youtube.com/@pinterzsoltai'

# Modell nevek és a hozzájuk tartozó adatok
# Minden modell egy szótár, ami tartalmazza:
# - 'name': A modell megjelenítési neve
# - 'filename': A fájlnév alaprésze kiterjesztés nélkül
# - 'open_source': Boolean érték, True ha letölthető/open source modell
# - 'provider': A modell szolgáltatója/cége
# - 'release_date': Megjelenés dátuma (YYYY-MM-DD formátum vagy None)
# - 'type': image-generation / image-editing / multimodal
# - 'tags': Címkék listája (pl. ['photorealistic', 'artistic'])
# - 'max_resolution': Maximális felbontás (pl. '1024x1024')
# - 'pricing': Árazási információ (pl. 'Free', '$0.04/image')
# - 'min_api_price_per_image': A legolcsóbb ismert API-ár USD-ben egy képre, ha van
# - 'api_available': Elérhető-e API-n keresztül
# - 'speed': Generálási sebesség (pl. 'fast', 'medium', 'slow')
# - 'video_url': YouTube-link; egyedi videóhoz írd át a modellnél megadott URL-t
# - 'website': A modell/szolgáltató weboldala (URL vagy None)
MODELS: Dict[str, Dict[str, Any]] = {
    'model-001': {
        'name': 'Grok',
        'filename': 'grok',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'xAI',
        'release_date': '2024-08-13',
        'type': 'image-generation',
        'tags': ['photorealistic', 'general'],
        'max_resolution': '1024x1024',
        'pricing': 'Subscription',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://x.ai',
    },
    'model-002': {
        'name': 'Gemini Flash 2.0',
        'filename': 'gemini-flash',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Google',
        'release_date': '2024-12-11',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '1024x1024',
        'pricing': 'Free tier available',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://deepmind.google',
    },
    'model-003': {
        'name': 'Imagen 3',
        'filename': 'imagen3',
        'video_url': 'https://youtu.be/meYXpnE1Exw',
        'open_source': False,
        'provider': 'Google',
        'release_date': '2024-05-14',
        'type': 'image-generation',
        'tags': ['photorealistic', 'artistic'],
        'max_resolution': '1024x1024',
        'pricing': '$0.04/image',
        'min_api_price_per_image': 0.04,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://deepmind.google',
    },
    'model-004': {
        'name': 'GPT Image 1',
        'filename': 'gpt-image-1',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'OpenAI',
        'release_date': '2025-03-25',
        'type': 'multimodal',
        'tags': ['general', 'multimodal', 'text-rendering'],
        'max_resolution': '1536x1024',
        'pricing': '$0.04/image',
        'min_api_price_per_image': 0.04,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://openai.com',
    },
    'model-005': {
        'name': 'v6.1',
        'filename': 'midjourneyv61',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Midjourney',
        'release_date': '2024-07-30',
        'type': 'image-generation',
        'tags': ['artistic', 'photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': 'Subscription ($10+/mo)',
        'api_available': False,
        'speed': 'medium',
        'website': 'https://midjourney.com',
    },
    'model-006': {
        'name': 'v7',
        'filename': 'midjourneyv7',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Midjourney',
        'release_date': '2025-04-03',
        'type': 'image-generation',
        'tags': ['artistic', 'photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': 'Subscription ($10+/mo)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://midjourney.com',
    },
    'model-007': {
        'name': 'Reve',
        'filename': 'reve',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Reve',
        'release_date': '2025-03-25',
        'type': 'image-generation',
        'tags': ['artistic', 'general'],
        'max_resolution': '2048x2048',
        'pricing': 'Free tier available',
        'api_available': True,
        'speed': 'fast',
        'website': None,
    },
    'model-008': {
        'name': 'I1',
        'filename': 'hidreami1',
        'video_url': 'https://youtu.be/qBdoKX3vmBE',
        'open_source': True,
        'provider': 'HiDream',
        'release_date': '2025-04-07',
        'type': 'image-generation',
        'tags': ['general', 'text-rendering'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://github.com/HiDream-ai',
    },
    'model-009': {
        'name': 'Lumina-Image-2.0',
        'filename': 'lumina2',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Alpha-VLLM',
        'release_date': '2025-01-25',
        'type': 'image-generation',
        'tags': ['general'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://github.com/Alpha-VLLM',
    },
    'model-010': {
        'name': 'Seedream 2.0 (CapCut Dreamina Image 2.0 Pro)',
        'filename': 'dreamina-image20pro',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'ByteDance',
        'release_date': '2024-09-09',
        'type': 'image-generation',
        'tags': ['photorealistic', 'general'],
        'max_resolution': '2048x2048',
        'pricing': 'Free tier available',
        'api_available': False,
        'speed': 'fast',
        'website': 'https://dreamina.capcut.com',
    },
    'model-011': {
        'name': 'Juggernaut XI',
        'filename': 'juggernautxl',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'RunDiffusion',
        'release_date': '2024-08-29',
        'type': 'image-generation',
        'tags': ['photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://rundiffusion.com',
    },
    'model-012': {
        'name': 'Fluxmania V',
        'filename': 'fluxmaniaV',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Community',
        'release_date': '2025-04-01',
        'type': 'image-generation',
        'tags': ['artistic', 'stylized'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://civitai.com/models/778691/fluxmania',
    },
    'model-013': {
        'name': 'Tengr.ai',
        'filename': 'tengrai',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Tengr.ai',
        'release_date': '2024-04-30',
        'type': 'image-generation',
        'tags': ['general'],
        'max_resolution': '1024x1024',
        'pricing': 'Free tier available',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://tengr.ai',
    },
    'model-014': {
        'name': 'Quantum',
        'filename': 'tengrai-q',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Tengr.ai',
        'release_date': '2025-02-11',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': 'Free tier available',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://tengr.ai',
    },
    'model-015': {
        'name': 'Firefly Image 4',
        'filename': 'firefly4',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Adobe',
        'release_date': '2025-04-24',
        'type': 'image-generation',
        'tags': ['photorealistic', 'artistic', 'commercial-safe'],
        'max_resolution': '2000x2000',
        'pricing': 'Subscription',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://www.adobe.com/products/firefly.html',
    },
    'model-016': {
        'name': 'Dreamina Seedream 3.0',
        'filename': 'dreamina-image3',
        'video_url': 'https://youtu.be/2UQCeb1h1hg',
        'open_source': False,
        'provider': 'ByteDance',
        'release_date': '2025-04-16',
        'type': 'image-generation',
        'tags': ['photorealistic', 'general'],
        'max_resolution': '2048x2048',
        'pricing': 'Free tier available',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://dreamina.capcut.com',
    },
    'model-017': {
        'name': '3.0',
        'filename': 'ideogram3',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Ideogram',
        'release_date': '2025-03-26',
        'type': 'image-generation',
        'tags': ['text-rendering', 'general', 'photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': 'Free tier available',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://ideogram.ai',
    },
    'model-018': {
        'name': 'Realistic V2',
        'filename': 'piclumen-realistic-v2',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Piclumen',
        'release_date': '2024-11-12',
        'type': 'image-generation',
        'tags': ['photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': 'Free tier available',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://piclumen.com',
    },
    'model-019': {
        'name': 'F Lite Standard',
        'filename': 'f-lite-standard',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Community',
        'release_date': '2025-04-29',
        'type': 'image-generation',
        'tags': ['general', 'lightweight'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': None,
    },
    'model-020': {
        'name': 'Gemini Flash 2.0 Preview 0507',
        'filename': 'gemini-2.0-flash-0507',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Google',
        'release_date': '2025-05-07',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '1024x1024',
        'pricing': 'Free tier available',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://deepmind.google',
    },
    'model-021': {
        'name': 'v7 20250501',
        'filename': 'midjourneyv7-20250501',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Midjourney',
        'release_date': '2025-05-01',
        'type': 'image-generation',
        'tags': ['artistic', 'photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': 'Subscription ($10+/mo)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://midjourney.com',
    },
    'model-022': {
        'name': 'Hunyuan Image 2.0',
        'filename': 'hunyuan-image-2.0',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Tencent',
        'release_date': '2025-05-16',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': '$0.03/image',
        'min_api_price_per_image': 0.03,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://hunyuan.tencent.com',
    },
    'model-023': {
        'name': 'Imagen 4',
        'filename': 'imagen4',
        'video_url': 'https://youtu.be/KApbyS09Rp8',
        'open_source': False,
        'provider': 'Google',
        'release_date': '2025-05-20',
        'type': 'image-generation',
        'tags': ['photorealistic', 'artistic', 'text-rendering'],
        'max_resolution': '2048x2048',
        'pricing': '$0.04/image',
        'min_api_price_per_image': 0.04,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://deepmind.google',
    },
    'model-024': {
        'name': 'V3 Raw',
        'filename': 'recraft-v3-raw',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Recraft',
        'release_date': '2024-10-30',
        'type': 'image-generation',
        'tags': ['photorealistic', 'artistic'],
        'max_resolution': '1024x1024',
        'pricing': 'Subscription',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://recraft.ai',
    },
    'model-025': {
        'name': 'BAGEL',
        'filename': 'bagel',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'ByteDance',
        'release_date': '2025-05-20',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://github.com/bytedance',
    },
    'model-026': {
        'name': 'FLUX.1 Kontext [pro]',
        'filename': 'flux1-kontext-pro',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Black Forest Labs',
        'release_date': '2025-05-29',
        'type': 'image-editing',
        'tags': ['editing', 'inpainting'],
        'max_resolution': '2048x2048',
        'pricing': '$0.04/image',
        'min_api_price_per_image': 0.04,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://blackforestlabs.ai',
    },
    'model-027': {
        'name': 'Chroma v34',
        'filename': 'chroma-34',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Community',
        'release_date': '2025-06-03',
        'type': 'image-generation',
        'tags': ['artistic', 'stylized'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://huggingface.co/lodestones',
    },
    'model-028': {
        'name': 'Ernie 4.5 Turbo',
        'filename': 'ernie-45turbo',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Baidu',
        'release_date': '2025-04-25',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '2048x2048',
        'pricing': 'Free tier available',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://yiyan.baidu.com',
    },
    'model-029': {
        'name': 'Imagen 4 Ultra',
        'filename': 'imagen4ultra',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Google',
        'release_date': '2025-07-24',
        'type': 'image-generation',
        'tags': ['photorealistic', 'artistic', 'text-rendering'],
        'max_resolution': '2048x2048',
        'pricing': '$0.08/image',
        'min_api_price_per_image': 0.08,
        'api_available': True,
        'speed': 'slow',
        'website': 'https://deepmind.google',
    },
    'model-030': {
        'name': 'Qwen-Image',
        'filename': 'qwen-image',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Alibaba Cloud',
        'release_date': '2025-08-04',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://qwen.ai',
    },
    'model-031': {
        'name': 'Gemini 2.5 Flash Image Preview',
        'filename': 'gemini25flashimagepreview',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Google',
        'release_date': '2025-08-26',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '1024x1024',
        'pricing': '$0.039/image',
        'min_api_price_per_image': 0.039,
        'api_available': True,
        'speed': 'fast',
        'website': 'https://deepmind.google',
    },
    'model-032': {
        'name': 'FLUX.1 Krea',
        'filename': 'flux1-krea',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Krea AI',
        'release_date': '2025-07-31',
        'type': 'image-generation',
        'tags': ['general', 'artistic'],
        'max_resolution': '1440x1440',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://krea.ai',
    },
    'model-033': {
        'name': 'Hunyuan Image 2.1',
        'filename': 'hunyuan-image-2.1',
        'video_url': 'https://youtu.be/dpIehQB8JGw',
        'open_source': True,
        'provider': 'Tencent',
        'release_date': '2025-09-08',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://hunyuan.tencent.com',
    },
    'model-034': {
        'name': 'Seedream 4.0 4k',
        'filename': 'seedream-4.0-4k',
        'video_url': 'https://youtu.be/94qxo-hC1Fc',
        'open_source': False,
        'provider': 'ByteDance',
        'release_date': '2025-09-09',
        'type': 'image-generation',
        'tags': ['photorealistic', 'high-resolution'],
        'max_resolution': '4096x4096',
        'pricing': '$0.04/image',
        'min_api_price_per_image': 0.04,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://dreamina.capcut.com',
    },
    'model-035': {
        'name': 'KOLORS 2.1',
        'filename': 'klingai-kolors-2.1',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Kling AI',
        'release_date': '2025-07-08',
        'type': 'image-generation',
        'tags': ['artistic', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': 'Subscription',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://klingai.com',
    },
    'model-036': {
        'name': 'HunyuanImage-3.0',
        'filename': 'hunyuan-image-3.0',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Tencent',
        'release_date': '2025-09-28',
        'type': 'image-generation',
        'tags': ['photorealistic', 'general'],
        'max_resolution': '4096x4096',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://hunyuan.tencent.com',
    },
    'model-037': {
        'name': 'GPT-5 Image Mini High',
        'filename': 'gpt-5-image-mini-high',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'OpenAI',
        'release_date': '2025-08-07',
        'type': 'multimodal',
        'tags': ['general', 'multimodal', 'text-rendering'],
        'max_resolution': '2048x2048',
        'pricing': '$0.02/image',
        'min_api_price_per_image': 0.02,
        'api_available': True,
        'speed': 'fast',
        'website': 'https://openai.com',
    },
    'model-038': {
        'name': 'GPT-5 Image Mini Low',
        'filename': 'gpt-5-image-mini-low',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'OpenAI',
        'release_date': '2025-08-07',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '1024x1024',
        'pricing': '$0.005/image',
        'min_api_price_per_image': 0.005,
        'api_available': True,
        'speed': 'fast',
        'website': 'https://openai.com',
    },
    'model-039': {
        'name': 'GPT-5 Image Mini Medium',
        'filename': 'gpt-5-image-mini-medium',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'OpenAI',
        'release_date': '2025-08-07',
        'type': 'multimodal',
        'tags': ['general', 'multimodal', 'text-rendering'],
        'max_resolution': '1536x1536',
        'pricing': '$0.01/image',
        'min_api_price_per_image': 0.01,
        'api_available': True,
        'speed': 'fast',
        'website': 'https://openai.com',
    },
    'model-040': {
        'name': 'MAI-Image-1',
        'filename': 'mai-image-1',
        'video_url': 'https://youtu.be/fG-AshWj1tU',
        'open_source': False,
        'provider': 'Microsoft',
        'release_date': '2025-10-13',
        'type': 'image-generation',
        'tags': ['photorealistic', 'general'],
        'max_resolution': '2048x2048',
        'pricing': '$0.03/image',
        'min_api_price_per_image': 0.03,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://azure.microsoft.com',
    },
    'model-041': {
        'name': 'Nano Banana Pro (Gemini 3 Pro Image)',
        'filename': 'nanobananapro-4k',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Google',
        'release_date': '2025-11-20',
        'type': 'multimodal',
        'tags': ['photorealistic', 'multimodal', 'text-rendering'],
        'max_resolution': '4096x4096',
        'pricing': '$0.06/image',
        'min_api_price_per_image': 0.06,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://deepmind.google',
    },
    'model-042': {
        'name': 'Z Image Turbo',
        'filename': 'z-image-turbo',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Alibaba Cloud',
        'release_date': '2025-11-25',
        'type': 'image-generation',
        'tags': ['general', 'fast'],
        'max_resolution': '2048x2048',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://qwen.ai',
    },
    'model-043': {
        'name': 'FLUX.2 [pro]',
        'filename': 'flux2-pro-2k',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Black Forest Labs',
        'release_date': '2025-11-25',
        'type': 'image-generation',
        'tags': ['photorealistic', 'artistic'],
        'max_resolution': '2048x2048',
        'pricing': '$0.05/image',
        'min_api_price_per_image': 0.05,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://blackforestlabs.ai',
    },
    'model-044': {
        'name': 'FLUX.2 [dev]',
        'filename': 'flux2-dev',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Black Forest Labs',
        'release_date': '2025-11-25',
        'type': 'image-generation',
        'tags': ['general', 'artistic'],
        'max_resolution': '2048x2048',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://blackforestlabs.ai',
    },
    'model-045': {
        'name': 'Omni Image 1.0',
        'filename': 'klingai-omni-image-1.0',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Kling AI',
        'release_date': '2025-12-01',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': 'Subscription',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://klingai.com',
    },
    'model-046': {
        'name': 'FLUX.2 [flex]',
        'filename': 'flux2-flex-2k',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Black Forest Labs',
        'release_date': '2025-11-25',
        'type': 'image-generation',
        'tags': ['general', 'flexible'],
        'max_resolution': '2048x2048',
        'pricing': '$0.04/image',
        'min_api_price_per_image': 0.04,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://blackforestlabs.ai',
    },
    'model-047': {
        'name': 'Seedream 4.5 4k',
        'filename': 'seedream-4.5-4k',
        'video_url': 'https://youtu.be/21_q6vUyUEU',
        'open_source': False,
        'provider': 'ByteDance',
        'release_date': '2025-12-03',
        'type': 'image-generation',
        'tags': ['photorealistic', 'high-resolution'],
        'max_resolution': '4096x4096',
        'pricing': '$0.035-$0.045/image',
        'min_api_price_per_image': 0.035,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://dreamina.capcut.com',
    },
    'model-048': {
        'name': 'GPT Image 1.5',
        'filename': 'gpt-image-1.5',
        'video_url': 'https://youtu.be/9KU74-9pDEw',
        'open_source': False,
        'provider': 'OpenAI',
        'release_date': '2025-12-16',
        'type': 'multimodal',
        'tags': ['general', 'multimodal', 'text-rendering'],
        'max_resolution': '1536x1024',
        'pricing': '$0.05/image',
        'min_api_price_per_image': 0.05,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://openai.com',
    },
    'model-049': {
        'name': 'Qwen-Image-2512',
        'filename': 'qwen-image-2512',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Alibaba Cloud',
        'release_date': '2025-12-31',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '1328x1328',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://qwen.ai',
    },
    'model-050': {
        'name': 'GLM-Image',
        'filename': 'glm-image',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Z.ai',
        'release_date': '2026-01-14',
        'type': 'image-generation',
        'tags': ['general'],
        'max_resolution': '2048x2048',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://open.bigmodel.cn',
    },
    'model-051': {
        'name': 'FLUX.2 [klein base] 9B',
        'filename': 'flux2-klein-base-9b',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Black Forest Labs',
        'release_date': '2026-01-15',
        'type': 'image-generation',
        'tags': ['general', 'lightweight'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://blackforestlabs.ai',
    },
    'model-052': {
        'name': 'FLUX.2 [klein distilled] 9B',
        'filename': 'flux2-klein-9b',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Black Forest Labs',
        'release_date': '2026-01-16',
        'type': 'image-generation',
        'tags': ['general', 'lightweight', 'fast'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://blackforestlabs.ai',
    },
    'model-053': {
        'name': 'FLUX.2 [klein base] 4B',
        'filename': 'flux2-klein-base-4b',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Black Forest Labs',
        'release_date': '2026-01-15',
        'type': 'image-generation',
        'tags': ['general', 'lightweight'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://blackforestlabs.ai',
    },
    'model-054': {
        'name': 'FLUX.2 [klein distilled] 4B',
        'filename': 'flux2-klein-4b',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Black Forest Labs',
        'release_date': '2026-01-15',
        'type': 'image-generation',
        'tags': ['general', 'lightweight', 'fast'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://blackforestlabs.ai',
    },
    'model-055': {
        'name': 'Z-Image Base',
        'filename': 'z-image-base',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'Alibaba Cloud',
        'release_date': '2026-01-27',
        'type': 'image-generation',
        'tags': ['general'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://qwen.ai',
    },
    'model-056': {
        'name': 'Grok Imagine Image 20260201',
        'filename': 'grok-imagine-image-20260201',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'xAI',
        'release_date': '2026-02-01',
        'type': 'image-generation',
        'tags': ['photorealistic', 'general'],
        'max_resolution': '2048x2048',
        'pricing': 'Subscription',
        'api_available': True,
        'speed': 'fast',
        'website': 'https://x.ai',
    },
    'model-057': {
        'name': 'Qwen-Image 2.0',
        'filename': 'qwen-image-2.0',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Alibaba Cloud',
        'release_date': '2026-02-10',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '2048x2048',
        'pricing': '$0.03/image',
        'min_api_price_per_image': 0.03,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://qwen.ai',
    },
    'model-058': {
        'name': 'BitDance',
        'filename': 'bitdance',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': True,
        'provider': 'ByteDance',
        'release_date': '2026-02-17',
        'type': 'image-generation',
        'tags': ['general', 'artistic'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'fast',
        'website': None,
    },
    'model-059': {
        'name': 'V4',
        'filename': 'recraft-v4',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Recraft',
        'release_date': '2026-02-17',
        'type': 'image-generation',
        'tags': ['photorealistic', 'artistic'],
        'max_resolution': '1024x1024',
        'pricing': '$0.04/image',
        'min_api_price_per_image': 0.04,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://recraft.ai',
    },
    'model-060': {
        'name': 'Seedream 5.0 lite 3k',
        'filename': 'seedream-5.0-lite',
        'video_url': 'https://youtu.be/aAdJhyTBT3A',
        'open_source': False,
        'provider': 'ByteDance',
        'release_date': '2026-02-13',
        'type': 'image-generation',
        'tags': ['photorealistic', 'high-resolution'],
        'max_resolution': '3072x3072',
        'pricing': '$0.035/image',
        'min_api_price_per_image': 0.035,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://dreamina.capcut.com',
    },
    'model-061': {
        'name': 'Nano Banana 2 4k',
        'filename': 'nanobanana-2-4k',
        'video_url': 'https://youtu.be/y3BH8sTo2nY',
        'open_source': False,
        'provider': 'Google',
        'release_date': '2026-02-26',
        'type': 'multimodal',
        'tags': ['photorealistic', 'multimodal', 'text-rendering'],
        'max_resolution': '4096x4096',
        'pricing': '$0.06/image',
        'min_api_price_per_image': 0.06,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://deepmind.google',
    },
    'model-062': {
        'name': 'Firefly Image 5 preview',
        'filename': 'firefly-image-5-preview',
        'video_url': 'https://youtu.be/vghXaZUSd5E',
        'open_source': False,
        'provider': 'Adobe',
        'release_date': '2025-10-28',
        'type': 'image-generation',
        'tags': ['general', 'editing', 'commercial-safe','layers'],
        'max_resolution': '2048x2048',
        'pricing': 'Subscription',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://firefly.adobe.com',
    },
    'model-063': {
        'name': 'HunyuanImage-3.0 Instruct',
        'filename': 'hunyuan-image-3.0-instruct',
        'video_url': 'https://youtu.be/WzU8jbmBvac',
        'open_source': True,
        'provider': 'Tencent',
        'release_date': '2026-01-26',
        'type': 'image-generation',
        'tags': ['general', 'multimodal', 'text-rendering'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': True,
        'speed': 'slow',
        'website': 'https://hunyuan.tencent.com',
    },
    'model-064': {
        'name': 'FLUX.2 [max]',
        'filename': 'flux2-max-2k',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Black Forest Labs',
        'release_date': '2025-11-25',
        'type': 'image-generation',
        'tags': ['photorealistic', 'artistic', 'high-resolution'],
        'max_resolution': '2048x2048',
        'pricing': '$0.07/image',
        'min_api_price_per_image': 0.07,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://blackforestlabs.ai',
    },
    'model-065': {
        'name': 'v8 alpha',
        'filename': 'midjourneyv8alpha',
        'video_url': 'https://youtu.be/oJm0V3_dzss',
        'open_source': False,
        'provider': 'Midjourney',
        'release_date': '2026-03-17',
        'type': 'image-generation',
        'tags': ['general', 'artistic', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': 'Subscription',
        'api_available': False,
        'speed': 'slow',
        'website': 'https://midjourney.com',
    },
    'model-066': {
        'name': 'MAI-Image-2',
        'filename': 'mai-image-2',
        'video_url': 'https://youtu.be/AkyoqcjUEIg',
        'open_source': False,
        'provider': 'Microsoft',
        'release_date': '2026-03-19',
        'type': 'image-generation',
        'tags': ['general', 'text-rendering'],
        'max_resolution': '1024x1024',
        'pricing': '$33/1M tokens',
        'api_available': True,
        'speed': 'medium',
        'website': 'https://www.microsoft.com/en-us/ai',
    },
    'model-067': {
        'name': 'Reve v1.5',
        'filename': 'reve-1.5',
        'video_url': 'https://youtu.be/OhWg3JVU_cw',
        'open_source': False,
        'provider': 'Reve AI',
        'release_date': '2026-02-23',
        'type': 'image-generation',
        'tags': ['general', '4k', 'photorealistic'],
        'max_resolution': '4096x4096',
        'pricing': '$0,024/image',
        'min_api_price_per_image': 0.024,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://reve.ai',
    },
    'model-068': {
        'name': 'Uni-1',
        'filename': 'uni-1',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'Luma AI',
        'release_date': '2026-03-23',
        'type': 'image-generation',
        'tags': ['general', 'reasoning', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': '$0,0909-$0,1101/image | $45,45/1M tokens',
        'min_api_price_per_image': 0.0909,
        'api_available': True,
        'speed': 'slow',
        'website': 'https://lumalabs.ai/',
    },
    'model-069': {
        'name': 'Wan 2.7-Image Pro 2k',
        'filename': 'wan-2-7-pro-2k',
        'video_url': 'https://youtu.be/ZV9QW-jR630',
        'open_source': False,
        'provider': 'Alibaba',
        'release_date': '2026-04-01',
        'type': 'image-generation',
        'tags': ['general', 'high-resolution', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': '$0,037-$0,06/image',
        'min_api_price_per_image': 0.037,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://x.com/Alibaba_Wan/status/2039329029241872767',
    },
    'model-070': {
        'name': 'v8.1 alpha',
        'filename': 'midjourney-v8.1-alpha',
        'video_url': 'https://youtu.be/mq0fLeYRyvg',
        'open_source': False,
        'provider': 'Midjourney',
        'release_date': '2026-04-14',
        'type': 'image-generation',
        'tags': ['general', 'artistic', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': 'Subscription',
        'api_available': False,
        'speed': 'fast',
        'website': 'https://midjourney.com',
    },
    'model-071': {
        'name': 'ERNIE-Image',
        'filename': 'ernie-image',
        'video_url': 'https://youtu.be/3EZmR0fHPHs',
        'open_source': True,
        'provider': 'Baidu',
        'release_date': '2026-04-15',
        'type': 'multimodal',
        'tags': ['general', 'multimodal', 'text-rendering'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': False,
        'speed': 'medium',
        'website': 'https://yiyan.baidu.com',
    },
    'model-072': {
        'name': 'ERNIE-Image Turbo',
        'filename': 'ernie-image-turbo',
        'video_url': 'https://youtu.be/r4nAjCkeSls',
        'open_source': True,
        'provider': 'Baidu',
        'release_date': '2026-04-15',
        'type': 'multimodal',
        'tags': ['general', 'multimodal', 'text-rendering'],
        'max_resolution': '1024x1024',
        'pricing': 'Free (Open Source)',
        'api_available': False,
        'speed': 'fast',
        'website': 'https://yiyan.baidu.com',
    },
    'model-073': {
        'name': 'ImagineArt 2.0',
        'filename': 'imagineart-2-0',
        'video_url': 'https://youtu.be/WNyEoTg7NeA',
        'open_source': False,
        'provider': 'ImagineArt',
        'release_date': '2026-04-16',
        'type': 'image-generation',
        'tags': ['general', 'artistic', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': '$0,03-$0,05/image',
        'min_api_price_per_image': 0.03,
        'api_available': False,
        'speed': 'medium',
        'website': 'https://imagineart.com',
    },
    'model-074': {
        'name': 'GPT Image 2 3k',
        'filename': 'gpt-image-2-3k',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'OpenAI',
        'release_date': '2026-04-21',
        'type': 'multimodal',
        'tags': ['general', 'multimodal', 'text-rendering'],
        'max_resolution': '2880x2880',
        'pricing': '$0,71157/image',
        'min_api_price_per_image': 0.71157,
        'api_available': True,
        'speed': 'slow',
        'website': 'https://openai.com',
    },
    'model-075': {
        'name': 'GPT Image 2 ChatGPT',
        'filename': 'gpt-image-2-chatgpt',
        'video_url': 'https://www.youtube.com/@pinterzsoltai',
        'open_source': False,
        'provider': 'OpenAI',
        'release_date': '2026-04-21',
        'type': 'multimodal',
        'tags': ['general', 'multimodal', 'text-rendering'],
        'max_resolution': '1254x1254',
        'pricing': 'Subscription',
        'api_available': True,
        'speed': 'slow',
        'website': 'https://openai.com',
    },
    'model-076': {
        'name': 'Uni-1.1',
        'filename': 'uni-1.1',
        'video_url': 'https://youtu.be/P3j472o2J5Q',
        'open_source': False,
        'provider': 'Luma AI',
        'release_date': '2026-05-05',
        'type': 'image-generation',
        'tags': ['general', 'reasoning', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': '$0.0404-$0.1/image',
        'min_api_price_per_image': 0.0404,
        'api_available': True,
        'speed': 'slow',
        'website': 'https://lumalabs.ai/',
    },
    'model-077': {
        'name': 'Lens',
        'filename': 'lens',
        'video_url': 'https://youtu.be/Eg-Z5XDvs38',
        'open_source': True,
        'provider': 'Microsoft',
        'release_date': '2026-05-15',
        'type': 'image-generation',
        'tags': ['general', 'text', 'photorealistic'],
        'max_resolution': '1440x1440',
        'pricing': 'Free (Open Source)',
        'api_available': False,
        'speed': 'slow',
        'website': 'https://huggingface.co/microsoft/Lens',
    },
    'model-078': {
        'name': 'Krea 2 Turbo (INT8)',
        'filename': 'krea2-turbo-int8',
        'video_url': 'https://youtu.be/6yaE9CQ8Ly0',
        'open_source': True,
        'provider': 'Krea.ai',
        'release_date': '2026-06-22',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': 'Free (Open Source)',
        'api_available': False,
        'speed': 'fast',
        'website': 'https://krea.ai',
    },
    'model-079': {
        'name': 'Uni-1.1 Max',
        'filename': 'uni-1.1-max',
        'video_url': 'https://youtu.be/P3j472o2J5Q',
        'open_source': False,
        'provider': 'Luma AI',
        'release_date': '2026-05-05',
        'type': 'image-generation',
        'tags': ['general', 'reasoning', 'photorealistic'],
        'max_resolution': '2048x2048',
        'pricing': '$0.1/image',
        'min_api_price_per_image': 0.1,
        'api_available': True,
        'speed': 'slow',
        'website': 'https://lumalabs.ai/',
    },
    'model-080': {
        'name': 'Seedream 5.0 Pro',
        'filename': 'seedream-5.0-pro',
        'video_url': 'https://youtu.be/Rt7p_oIBQB0',
        'open_source': False,
        'provider': 'ByteDance',
        'release_date': '2026-07-08',
        'type': 'image-generation',
        'tags': ['general', 'editing', 'photorealistic','minimal text'],
        'max_resolution': '2048x2048',
        'pricing': '$0.09/image',
        'min_api_price_per_image': 0.09,
        'api_available': True,
        'speed': 'slow',
        'website': 'https://www.bytedance.com/',
    },
    'model-081': {
        'name': 'MAI-Image-2.5',
        'filename': 'mai-image-2-5',
        'video_url': 'https://youtu.be/G29mcWF8wWQ',
        'open_source': False,
        'provider': 'Microsoft',
        'release_date': '2026-06-02',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': '$0.05/image',
        'min_api_price_per_image': 0.05,
        'api_available': True,
        'speed': 'slow',
        'website': 'https://microsoft.ai/models/mai-image-2-5/', 
    },
    'model-082': {
        'name': 'MAI-Image-2.5 Flash',
        'filename': 'mai-image-2-5-flash',
        'video_url': 'https://youtu.be/ybzlsMyR6Ug',
        'open_source': False,
        'provider': 'Microsoft',
        'release_date': '2026-06-02',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': '$0.02/image',
        'min_api_price_per_image': 0.02,
        'api_available': True,
        'speed': 'slow',
        'website': 'https://microsoft.ai/models/mai-image-2-5/', 
    },
    'model-083': {
        'name': 'MAI-Image-2.5 Pro',
        'filename': 'mai-image-2-5-pro',
        'video_url': 'https://youtu.be/UCW9KxwRDNU',
        'open_source': False,
        'provider': 'Microsoft',
        'release_date': '2026-06-02',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '1024x1024',
        'pricing': '$0.106/image',
        'min_api_price_per_image': 0.106,
        'api_available': True,
        'speed': 'medium',
        'website': 'https://microsoft.ai/models/mai-image-2-5/', 
    },
    'model-084': {
        'name': 'Qwen-Image 3.0',
        'filename': 'qwen-image-3.0',
        'video_url': 'https://youtu.be/AteWNuXVQWc',
        'open_source': False,
        'provider': 'Alibaba Cloud',
        'release_date': '2026-07-21',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '2048x2048',
        'pricing': '$0.03/image',
        'min_api_price_per_image': 0.03,
        'api_available': True,
        'speed': 'fast',
        'website': 'https://qwen.ai',
    },
    'model-085': {
        'name': 'Qwen-Image 3.0 Pro',
        'filename': 'qwen-image-3.0-pro',
        'video_url': 'https://youtu.be/AteWNuXVQWc',
        'open_source': False,
        'provider': 'Alibaba Cloud',
        'release_date': '2026-07-21',
        'type': 'multimodal',
        'tags': ['general', 'multimodal'],
        'max_resolution': '2048x2048',
        'pricing': '$0.04-$0.075/image',
        'min_api_price_per_image': 0.04,
        'api_available': True,
        'speed': 'fast',
        'website': 'https://qwen.ai',
    },
    'model-086': {
        'name': 'MAI-Image-2.6 Preview',
        'filename': 'mai-image-2-6-pre',
        'video_url': 'https://youtu.be/x9XVXBxq_6s',
        'open_source': False,
        'provider': 'Microsoft',
        'release_date': '2026-08-10',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '1536x1536',
        'pricing': '',
        'api_available': True,
        'speed': 'slow',
        'website': '', 
    },
    'model-087': {
        'name': 'GPT Image 2.5 Sunburst 4k Max',
        'filename': 'gpt-image-2-5-sunburst-4k-max',
        'video_url': 'https://youtu.be/MWB3MH1lfho',
        'open_source': False,
        'provider': 'OpenAI',
        'release_date': '2026-09-08',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '2880x2880',
        'pricing': '$0.71157/image',
        'min_api_price_per_image': 0.71157,
        'api_available': True,
        'speed': 'fast',
        'website': 'https://openai.com/hu-HU/index/introducing-chatgpt-images-2-5/', 
    },
    'model-088': {
        'name': 'GPT Image 2.5 Sunburst 1k Low',
        'filename': 'gpt-image-2-5-sunburst-1k-low',
        'video_url': 'https://youtu.be/tY6dn7RwQmw',
        'open_source': False,
        'provider': 'OpenAI',
        'release_date': '2026-09-08',
        'type': 'image-generation',
        'tags': ['general', 'photorealistic'],
        'max_resolution': '1536x1024',
        'pricing': '$0.00474/image',
        'min_api_price_per_image': 0.00474,
        'api_available': True,
        'speed': 'fast',
        'website': 'https://openai.com/hu-HU/index/introducing-chatgpt-images-2-5/', 
    }
}

# Engedélyezett képkiterjesztések listája
ALLOWED_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp']

# ELO Rating beállítások
DEFAULT_ELO = 1500  # Alapértelmezett ELO érték új modellekhez
K_FACTOR = 32       # K-faktor - a magasabb érték nagyobb változást eredményez győzelemkor/vereségkor

# Felhasználói élmény beállítások
REVEAL_DELAY_MS = 2000  # Szavazás után a modellek neveinek megjelenítési ideje milliszekundumban

# Befagyasztott modellek beállítások
# Az alkalmazás indításakor a leaderboard alsó N modellje "befagyasztásra" kerül.
# A befagyasztott modellek nem vesznek részt az Arena Battle-ben, de a Side-by-Side-ban láthatók.
FROZEN_BOTTOM_COUNT = 0  # Hány modellt fagyasszunk be az aljáról (0 = kikapcsolva)

# Új modellek boost beállítások (Arena Battle)
# Ha egy modellnek kevesebb meccse van, mint NEW_MODEL_BOOST_THRESHOLD, akkor
# NEW_MODEL_BOOST_WEIGHT-szer nagyobb eséllyel jelenik meg az egyik battle-slotban.
# A másik slot teljesen véletlenszerű marad. 50 meccs felett visszaáll a normál random.
NEW_MODEL_BOOST_THRESHOLD = 50  # Ennyi meccs alatt aktív a boost
NEW_MODEL_BOOST_WEIGHT = 20       # Hányszoros esély az átlagos modellhez képest

# Authentication beállítások
DEFAULT_SECRET_KEY = 'dev-secret-key-change-in-production'
SECRET_KEY = os.environ.get('SECRET_KEY', DEFAULT_SECRET_KEY)
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GITHUB_CLIENT_ID = os.environ.get('GITHUB_CLIENT_ID', '')
GITHUB_CLIENT_SECRET = os.environ.get('GITHUB_CLIENT_SECRET', '')
